export const atomicHabitsProgram = {
  0: {
    quote: "Start small, think big.",
    tasks: [{ activity: "Meditation", detail: "5 min breathing", time: "5 minutes" }],
    notes: "",
    completed: false,
  },
  1: {
    quote: "Consistency is key.",
    tasks: [{ activity: "Morning Walk", detail: "Walk 10 min outside", time: "10 minutes" }],
    notes: "",
    completed: false,
  },
  2: {
    quote: "Knowledge is power.",
    tasks: [{ activity: "Read Book", detail: "Read 10 pages", time: "15 minutes" }],
    notes: "",
    completed: false,
  },
  3: {
    quote: "Move your body, move your mind.",
    tasks: [{ activity: "Stretching", detail: "Full body stretches", time: "10 minutes" }],
    notes: "",
    completed: false,
  },
  4: {
    quote: "Reflect to grow.",
    tasks: [{ activity: "Journal", detail: "Write morning thoughts", time: "5 minutes" }],
    notes: "",
    completed: false,
  },
  5: {
    quote: "Hydrate and feel alive.",
    tasks: [{ activity: "Hydration", detail: "Drink 2 glasses of water", time: "5 minutes" }],
    notes: "",
    completed: false,
  },
  6: {
    quote: "Gratitude turns what we have into enough.",
    tasks: [{ activity: "Gratitude", detail: "Write 3 things you’re grateful for", time: "5 minutes" }],
    notes: "",
    completed: false,
  },
  7: {
    quote: "Breathe deeply, live fully.",
    tasks: [{ activity: "Deep Breathing", detail: "4-7-8 breathing exercise", time: "5 minutes" }],
    notes: "",
    completed: false,
  },
  8: {
    quote: "Plan your day, own your life.",
    tasks: [{ activity: "Plan Day", detail: "Write top 3 priorities", time: "10 minutes" }],
    notes: "",
    completed: false,
  },
  9: {
    quote: "Disconnect to reconnect.",
    tasks: [{ activity: "Digital Detox", detail: "No phone for 1 hour", time: "60 minutes" }],
    notes: "",
    completed: false,
  },
  10: {
    quote: "Strong body, strong mind.",
    tasks: [{ activity: "Exercise", detail: "Bodyweight workout", time: "15 minutes" }],
    notes: "",
    completed: false,
  },
  11: {
    quote: "Learn something new every day.",
    tasks: [{ activity: "Learn Skill", detail: "Practice coding/learning", time: "30 minutes" }],
    notes: "",
    completed: false,
  },
  12: {
    quote: "Be mindful of your thoughts.",
    tasks: [{ activity: "Mindfulness", detail: "Observe your thoughts", time: "10 minutes" }],
    notes: "",
    completed: false,
  },
  13: {
    quote: "Declutter your space, declutter your mind.",
    tasks: [{ activity: "Declutter", detail: "Organize workspace", time: "15 minutes" }],
    notes: "",
    completed: false,
  },
  14: {
    quote: "Read to feed your mind.",
    tasks: [{ activity: "Reading", detail: "Read an article/book chapter", time: "20 minutes" }],
    notes: "",
    completed: false,
  },
  15: {
    quote: "Step outside, refresh your mind.",
    tasks: [{ activity: "Walk Outside", detail: "10 min walk for fresh air", time: "10 minutes" }],
    notes: "",
    completed: false,
  },
  16: {
    quote: "Reflect, learn, improve.",
    tasks: [{ activity: "Reflection", detail: "Review the day", time: "5 minutes" }],
    notes: "",
    completed: false,
  },
  17: {
    quote: "Stretch to stay flexible.",
    tasks: [{ activity: "Stretch & Move", detail: "Stretch for flexibility", time: "10 minutes" }],
    notes: "",
    completed: false,
  },
  18: {
    quote: "Create to express yourself.",
    tasks: [{ activity: "Creative Time", detail: "Draw, write, or music", time: "20 minutes" }],
    notes: "",
    completed: false,
  },
  19: {
    quote: "Calm mind, restful sleep.",
    tasks: [{ activity: "Evening Meditation", detail: "Calm mind before bed", time: "10 minutes" }],
    notes: "",
    completed: false,
  },
  20: {
    quote: "Review, plan, improve.",
    tasks: [{ activity: "Review Habits", detail: "Check your progress & notes", time: "10 minutes" }],
    notes: "",
    completed: false,
  },
};
